name: build-and-deploy

on:
  workflow_run:
    workflows: ["preprocessing-data", "main-to-release"]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout release branch
        uses: actions/checkout@v3
        with:
          ref: release

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: check
        run: |
          ls -al
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
