name: build-and-deploy

on:
  workflow_run:
    workflows: ["preprocessing-data", "main-to-release"]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout release branch
        uses: actions/checkout@v3
        with:
          ref: release

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Check dist exists
        run: |
          set -eux
          pwd
          ls -l
          ls -l dist
      - name: Upload to GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist

  deploy:
    needs: upload
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
