name: Deploy to GitHub Pages

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout release branch
        uses: actions/checkout@v3
        with:
          ref: release

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Setup Git user
        run: |
          git config user.name  "action"
          git config user.email "action@github.com"

      - name: Commit and push dist folder
        run: |
          git add dist
          git commit -m "Build and deploy to GitHub Pages"
          git push origin release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
