name: preprocessing-data
on: [push]
jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          echo "test"
      - name: "git commit"
        run: |
          date > generated.txt
          git config user.name  "action"
          git config user.email "action@github.com"
          git add .
          git commit -m "fetch data $(date -u +'%Y-%m-%d %H:%M:%S %Z')"
          git push
