name: preprocessing-data
on: [push]
jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: "get data"
        run: |
          ./scripts/get_data.sh
      - name: Count changes
        id: changes
        run: |
          set -x
          git add -N .
          echo "count=$(git diff --name-only | wc -l)" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: "git commit & push"
        run: |
          git config user.name  "action"
          git config user.email "action@github.com"
          git commit -m "fetch data $(date -u +'%Y-%m-%d %H:%M:%S %Z')"
          git push
        if: ${{ steps.changes.outputs.count > 0 }}
